### ISSUE TITLE
Buildinfo is not always available

### ISSUE THREAD

**Issue by 06kellyjac** [kubernetes-sigs/release-utils#59]
I package for nixpkgs and in our builds we don't have `.git` either because we fetch the release source tar.gz which doesn't have `.git` or we do a git clone and then delete the `.git` dir because it's not reproducible.

I believe debian also handles things in a similar way since someone working on debian posted a script that should be able to clean up the `.git` dir

https://github.com/NixOS/nixpkgs/issues/100498#issuecomment-1162917591 (cc: @Nihlus)

We *could* apply the script to the `.git` dir and keep it but just being able to set the ldflags is probably still desirable, especially since there are some cases of people complaining about buildinfo breaking reproducibility and people wanting to strip it

https://github.com/golang/go/issues/52372

And after https://go-review.googlesource.com/c/go/+/414794/ `-trimpath` will allow for removing it

**Comment by saschagrunert** [comment]
Hey @06kellyjac and @Nihlus, thank you for opening this issue.

Are we speaking about this part of the library?
https://github.com/kubernetes-sigs/release-utils/blob/352552eccc67401676d798ebd131ea49a2a86986/version/version.go#L67-L81

I guess you can inject at least the `gitVersion` via `-X`, for example:

```go
package main

import (
	"fmt"

	"sigs.k8s.io/release-utils/version"
)

func main() {
	fmt.Print(version.GetVersionInfo().GitVersion)
}
```

```
> go run -ldflags '-X sigs.k8s.io/release-utils/version.gitVersion=foobar' main.go
foobar
```

Would the same approach work for the other variables? (It does not work right now because of the "unknown" fallback in the code).

**Comment by 06kellyjac** [comment]
yep, just `gitVersion` falls back, the rest dont

https://github.com/sigstore/rekor/issues/913

**Comment by saschagrunert** [comment]
Having a fix in mind in https://github.com/kubernetes-sigs/release-utils/pull/61
